#### PRODUCT API's ####
GET http://localhost:4000/products/product/1/4
###
GET http://localhost:4000/products/product/1
###
PUT http://localhost:4000/products/product/1
Content-Type: application/json

{
    "id": 1,
    "name": "Iphone14ProUp",
    "description": "8gb-RAM,256gb-SSD Solid-Black",
    "price": 140000,
    "categoryId": 3,
    "discountId": 1,
    "inventoryId": 1
}

###
POST http://localhost:4000/products/product/create
Content-Type: application/json

{
    "name": "RealmePro9",
    "description": "6gb-RAM,256gb-SSD Solid-Gold",
    "price": 14030,
    "categoryId": 3,
}

###
DELETE http://localhost:4000/products/product/6

#### CATEGORY API's ####
GET http://localhost:4000/categories/allcategories/1/4
###
GET http://localhost:4000/categories/category/3
###
GET http://localhost:4000/categories/category/3/products
###
PUT http://localhost:4000/categories/category/5
Content-Type: application/json

{
    "id":5,
    "name":"Home and Kitchen",
    "description":"Spoons,Plates and Home Utensils"
}
###
POST http://localhost:4000/categories/category/create
Content-Type: application/json

{
    "id": 5,
    "name": "Home and Kitchen",
    "description": "Spoons,Plates,cups,Dishes,Grinders"
}
###
DELETE http://localhost:4000/categories/category/5

#### CARTITEMS API's ####
GET http://localhost:4000/cart/cartItems
###
POST http://localhost:4000/cart/cartItems/add/1
Content-Type: application/json

{
    "id":1,
    "cartId":1,
    "productId":2,
    "quantity":1
}
###
DELETE http://localhost:4000/cart/cartItems/user/1/product/2
###
DELETE http://localhost:4000/cart/cartItems/clear/user/1
###
GET http://localhost:4000/cart/cartItmes/checkoutCart/user/1

#### DISCOUNT API's ####
